# Generated by Django 2.1.7 on 2019-03-21 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EveNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_id', models.IntegerField()),
                ('eve_name', models.CharField(max_length=500)),
                ('eve_catagory', models.CharField(choices=[('alliance', 'alliance'), ('character', 'character'), ('corporation', 'corporation')], max_length=30)),
                ('blacklisted', models.BooleanField(default=False)),
                ('added_by', models.CharField(max_length=500)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
            ],
            options={
                'permissions': (('view_eve_notes', 'Can view all eve notes'), ('add_new_eve_notes', 'Can add new eve notes')),
            },
        ),
        migrations.CreateModel(
            name='EveNoteComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=500)),
                ('comment', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('eve_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='toolbox.EveNote')),
            ],
            options={
                'permissions': (('view_eve_note_comments', 'Can view eve note comments'), ('add_new_eve_note_comments', 'Can add comments on eve notes')),
            },
        ),
        migrations.CreateModel(
            name='EveNoteRestrictedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=500)),
                ('comment', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('eve_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_comment', to='toolbox.EveNote')),
            ],
            options={
                'permissions': (('view_eve_note_restricted_comments', 'Can view restricted eve note comments'), ('add_new_eve_note_restricted_comments', 'Can add new restricted comments to eve notes')),
            },
        ),
    ]
