# Generated by Django 2.1.7 on 2019-03-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenote',
            options={'permissions': (('view_eve_notes', 'Can view all eve notes'), ('add_new_eve_notes', 'Can add new eve notes'), ('view_eve_blacklist', 'Can View the Blacklist'))},
        ),
    ]
