# Generated by Django 2.1.7 on 2019-03-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0002_auto_20190321_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenoterestrictedcomment',
            name='eve_note',
        ),
        migrations.AlterModelOptions(
            name='evenotecomment',
            options={'permissions': (('view_eve_note_comments', 'Can view eve note comments'), ('add_new_eve_note_comments', 'Can add comments on eve notes'), ('view_eve_note_restricted_comments', 'Can view restricted eve note comments'), ('add_new_eve_note_restricted_comments', 'Can add new restricted comments to eve notes'))},
        ),
        migrations.AddField(
            model_name='evenotecomment',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='EveNoteRestrictedComment',
        ),
    ]
