# Generated by Django 2.1.7 on 2019-04-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0003_auto_20190321_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenote',
            options={'permissions': (('view_eve_notes', 'Can view all eve notes'), ('add_new_eve_notes', 'Can add new eve notes'), ('view_eve_blacklist', 'Can View the Blacklist'), ('view_restricted_eve_notes', 'Can View restricted eve notes'), ('view_ultra_restricted_eve_notes', 'Can View ultra_restricted eve notes'), ('add_restricted_eve_notes', 'Can Add restricted eve notes'), ('add_ultra_restricted_eve_notes', 'Can Add ultra_restricted eve notes'))},
        ),
        migrations.AddField(
            model_name='evenote',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evenote',
            name='ultra_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
