# Generated by Django 2.1.7 on 2019-04-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0004_auto_20190419_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenote',
            options={'permissions': (('view_eve_notes', 'Can view all eve notes'), ('add_new_eve_notes', 'Can add new eve notes'), ('add_to_blacklist', 'Can add to Blacklist'), ('view_eve_blacklist', 'Can View the Blacklist'), ('view_restricted_eve_notes', 'Can View restricted eve notes'), ('view_ultra_restricted_eve_notes', 'Can View ultra_restricted eve notes'), ('add_restricted_eve_notes', 'Can Add restricted eve notes'), ('add_ultra_restricted_eve_notes', 'Can Add ultra_restricted eve notes'))},
        ),
    ]
