# Generated by Django 2.2.2 on 2019-09-05 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0006_auto_20190425_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_hash', models.CharField(default=None, max_length=255, null=True, unique=True)),
                ('name', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EveCharacterMining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_id', models.IntegerField()),
                ('eve_name', models.CharField(max_length=500)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('month', models.DateTimeField()),
                ('raw_data', models.TextField()),
                ('isk_total', models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EveStructureMining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer_id', models.IntegerField()),
                ('observer_name', models.CharField(max_length=500)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('month', models.DateTimeField()),
                ('isk_total', models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiKeyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField(default=None, null=True)),
                ('date_accessed', models.DateTimeField(auto_now=True)),
                ('apikey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.ApiKey')),
            ],
        ),
    ]
