# Generated by Django 2.2.2 on 2019-10-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0007_apikey_apikeylog_evecharactermining_evestructuremining'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterMining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField()),
                ('character_name', models.CharField(max_length=500)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('isk_total', models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True)),
                ('tax_total', models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterMiningObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ore_name', models.CharField(max_length=500)),
                ('ore_type', models.IntegerField()),
                ('count', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.CharacterMining')),
            ],
        ),
        migrations.DeleteModel(
            name='EveCharacterMining',
        ),
        migrations.DeleteModel(
            name='EveStructureMining',
        ),
    ]
