# Generated by Django 2.2.2 on 2019-10-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0010_characterpayment_tras_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterpayment',
            old_name='tras_id',
            new_name='trans_id',
        ),
    ]
