# Generated by Django 2.2.2 on 2019-10-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0011_auto_20191004_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactermining',
            options={'permissions': (('view_own_character_mining', 'Can View Personal Mining Taxes'), ('admin_alliance_mining', 'Can View all Ledger Data'))},
        ),
    ]
