# Generated by Django 2.2 on 2019-11-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0012_auto_20191026_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactermining',
            options={'permissions': (('view_own_character_mining', 'Can View Personal Mining Taxes'), ('admin_alliance_mining', 'Can View all Ledger Data'), ('admin_corporation_mining', 'Can View Own Corps Ledger Data'))},
        ),
    ]
