# Generated by Django 2.2.9 on 2020-03-16 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0013_auto_20191102_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoonExtraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_id', models.BigIntegerField()),
                ('structure_name', models.CharField(max_length=500)),
                ('moon_name', models.CharField(max_length=500)),
                ('extraction_complete', models.DateTimeField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoonExtractionOre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ore', models.CharField(max_length=500)),
                ('ore_percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_m3', models.BigIntegerField()),
                ('mined_m3', models.BigIntegerField()),
                ('moon_timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.MoonExtraction')),
            ],
        ),
    ]
