# Generated by Django 3.2.5 on 2021-07-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0014_moonextraction_moonextractionore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolboxEveNoteFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Smart Filter: User Has Flagged/Blacklisted Char',
                'verbose_name_plural': 'Smart Filter: User Has Flagged/Blacklisted Char',
            },
        ),
    ]
